language: python
python:
  - 3.5
install:
  - pip install -r test-requirements.txt --use-wheel
  - pip install -q coverage coveralls --use-wheel
script:
  - coverage run --source=sphinxcontrib.deckjs setup.py test
after_success:
  - coveralls
notifications:
  email: false
